### ISSUE TITLE
[Encurtador de URL] Node.js + MySQL + Express

### ISSUE THREAD

**Issue by victornovaiss** [backend-br/desafios#10]
## Repositório do desafio 

https://github.com/victornovaiss/encurtador-url

## Stack 

- NodeJs 
- MySQL
- Express

## Comentários 

Estou tentando aprender programação sozinho e acho muito importante participar de desafios concretos como os propostos por esse repositório.

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
