### ISSUE TITLE
[Encurtador URL]Golang

### ISSUE THREAD

**Issue by Davi-Arauj** [backend-br/desafios#11]
## Repositório do desafio 

[Encurtador Url](https://github.com/Davi-Arauj/desafio-encurtadorURL)

## Stack 

* Golang
* Postgres

## Comentários 

Estava a procura de novas idéias de código e encontrei estes desafios que pretendo realizar mais alguns logo, este foi bem desafiador pois sou iniciante na linguagem Golang, tem um requisito do desafio que eu não consegui concluir, foi deixar os dados armazenado temporário, consegui criar a tabela temporária e até inserir dados na mesma usando o PGADMIN, porém quando a api vai fazer alguma transação com a tabela dá um erro "pq: relation "url" does not exist", onde url é o nome da tabela,, então resolvi concluir o desafio com uma tabela permanente por enquanto eu aprendo a trabalhar com tabelas temporárias.

## Contato 

[Linkedin](https://www.linkedin.com/in/davi-ara%C3%BAjo-9742b071/)
[Email](moreiradaavi@gmail.com)

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
