### ISSUE TITLE
Tipo de Criptografia sugerida incorreta

### ISSUE THREAD

**Issue by Gabrielsoac** [backend-br/desafios#111]
No desafio de criptografia, há uma sugestão de uso de algoritmos como SHA-512 e PBKDF2, porém esses são algoritmos de hash, utilizamos para realizar comparações no DB, eles não realizam descriptografia, então não há como obter os dados após persistidos no DB.

O correto seria sugerir algoritmos simétricos como o DES e AES ou assimétricas como SSH (não tão indicado).

**Comment by Gabrielsoac** [comment]
O problema do tipo de criptografia está no desafio proposto, onde devemos utilizar de criptografia para inserir dados, mas também para obter os dados, de acordo com esta parte do desafio:

"realizando a criptografia em tempo de execução durante a conversão da entidade para a coluna correspondente no banco de dados, e vice-versa."

**Comment by gustavofreze** [comment]
Obrigado pela contribuição. Sinta-se a vontade para abrir um PR, e alterar as sugestões.

**Comment by Gabrielsoac** [comment]
> Obrigado pela contribuição. Sinta-se a vontade para abrir um PR, e alterar as sugestões.

Claro! Vou enviar :)
