### ISSUE TITLE
[CRIPTOGRAFIA]Golang

### ISSUE THREAD

**Issue by Davi-Arauj** [backend-br/desafios#12]
## Repositório do desafio 

[Desafio-Criptografia](https://github.com/Davi-Arauj/criptografia)

## Comentários 

Uma das principais razões é a busca de conhecimento, tenho uma questão ainda há resolver, onde salvar a chave privada, para que possa desligar o sistema e ao retorna eu consiga decodificar os dados.

## Contato 
[Linkedin](https://www.linkedin.com/in/davi-ara%C3%BAjo-9742b071/)
[Email](moreiradaavi@gmail.com)

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/cryptography/SOLUTIONS.md). Obrigado por contribuir :)
