### ISSUE TITLE
[Criptografia] Node + TypeScript + Sqlite

### ISSUE THREAD

**Issue by rms-diego** [backend-br/desafios#14]
## Repositório do desafio 
<a href="https://github.com/Drb-Diego/desafio-2-backend-br">Link do repositorio</a>

 

## Stack 

- NodeJs 
- Sqlite
- Typescript
- jwt
- prisma

## Comentários 

 
Exercitar o conhecimento na criação de apis rest seguindo os padrões RESTful.

 
## Contato 

<a href="https://www.linkedin.com/in/diego-rbrito/">Linkedin</a>
<a href="https://github.com/Drb-Diego">Github</a>

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/cryptography/SOLUTIONS.md). Obrigado por contribuir :)
