### ISSUE TITLE
[Encurtador de URL] Python + Postgresql + Redis + Docker

### ISSUE THREAD

**Issue by MichaelDeMattos** [backend-br/desafios#18]
## Repositório do desafio 

https://github.com/MichaelDeMattos/short-url

## Stack 

- Python
- Postgresql
-  Redis
-  Docker 

## Comentários 

Testar a utilização de novas tecnologias.

## Contato 

https://br.linkedin.com/in/michael-m-ortiz-57690a17a

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
