### ISSUE TITLE
[Pontos de interesse por GPS] Java + SpringBoot

### ISSUE THREAD

**Issue by eliasmarts** [backend-br/desafios#19]
## Repositório do desafio 

[Repositório](https://github.com/eliasmarts/pontos-interesse-GPS)

## Stack 
- Java
- SpringBoot
- MySQL

## Comentários 
Minha primeira vez fazendo um serviço REST, achei bem interessante o desafio, estava procurando coisas assim para consolidar o aprendizado de cursos que fiz na internet, pois a prática ajuda muito. Tive dificuldade em planejar os endpoints.

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/points-of-interest/SOLUTIONS.md). Obrigado por contribuir :)
