### ISSUE TITLE
[Encurtador de URL] Java, SpringBoot

### ISSUE THREAD

**Issue by tyronedamasceno** [backend-br/desafios#2]
## Repositório do desafio 
https://github.com/tyronedamasceno/URLShortener

## Stack 

- Java 8 
- SpringBoot 
- H2 Database

## Comentários 

Utilizei a conversão dos IDs da URL para base 62 (digitos+lowercase+uppercase) visto que nesta estratégia o tamanho das url crescem de forma bastante lenta, atingindo o objetivo de urls curtas.

Acredito que o redirecionamento da página não está feito da melhor forma possível, porém foi o melhor que consegui **por enquanto**! 

## Contato 
tyronedamasceno@gmail.com
[Facebook](https://www.facebook.com/tyrone.damasceno)

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
