### ISSUE TITLE
[EncurtadorDeURL] Java, SpringBoot

### ISSUE THREAD

**Issue by tuliorsc10** [backend-br/desafios#20]
## Repositório do desafio 

https://github.com/tuliorsc10/encurtadorUrl 

## Stack 
 
- JAVA
- SpringBoot 
- SqlServer
 

## Comentários 

 Estudar um pouco de Java 
 
## Contato 

(tt) @tuliorsc10

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
