### ISSUE TITLE
[Encurtador de URL] Javascript, NodeJS, MySQL

### ISSUE THREAD

**Issue by Estevamrod** [backend-br/desafios#22]
## Repositório do desafio 

https://github.com/Estevamrod/desafio/tree/main

## Stack 

 
- NodeJs 
- MySQL
- Sequelize
- Express 

## Comentários 
Praticar minhas habilidades com Nodejs e também javascript.

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
