### ISSUE TITLE
Permissão para inserir repo com solução de desafio

### ISSUE THREAD

**Issue by lucazpinheiro** [backend-br/desafios#37]
Olá,

Terrminei uma implementação do desafio do serviço de emprestimos, vi que no arquivo solutions.md, existe o link para uma solução escrita em em Java, gostaria de saber se estão aceitando outras soluções para adicionar nessa lista? Tentei abrir um PR adicionando o link do meu repositorio, mas não tenho permissões necessárias pra abrir o PR :confused:.

Solução feita com Node e typescript: https://github.com/lucazpinheiro/loans-service/

**Comment by gustavofreze** [comment]
Sim, soluções sempre são aceitas. Sobre o PR, você tem que fazer um fork desse repositório, e a partir daí abrir seu PR.

**Comment by lucazpinheiro** [comment]
@gustavofreze Opa, valeu pelo retorno, fiz o fork e abri o PR com a solução. Vou deixar aqui para quando puder dar uma olhada: https://github.com/backend-br/desafios/pull/38
