### ISSUE TITLE
[Encurtador de URL] Node.js + MongoDb

### ISSUE THREAD

**Issue by devGuerra** [backend-br/desafios#4]
## Link do Repositório 
[urlShortener](https://github.com/prosaka/urlShortener)

## Stack
- Node.js
- Express
- Mongoose
- MongoDB

## Comentarios
- Resolvi participar do desafio para entender um pouco mais sobre Node, estou aprendendo a uma semana e gostando demais. 

## Contato
[Twitter](https://twitter.com/ProSaka)
[LinkedIn](https://linkedin.com/in/umroberto/)

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
