### ISSUE TITLE
[Encurtador de URL] Node.js + Typescript

### ISSUE THREAD

**Issue by goncadanilo** [backend-br/desafios#5]
## Repositório do desafio 

[url-shortener](https://github.com/goncadanilo/url-shortener)

## Stack 

- Node.js
- Typescript
- Express
- MongoDB 
- Mongoose

## Comentários 

- Resolvi participar do desafio para testar meus conhecimentos com Node.js :)

## Contato 

Meu [LinkedIn: https://www.linkedin.com/in/goncadanilo](https://www.linkedin.com/in/goncadanilo/).
Meu [E-mial: gonca.danilo@gmal.com](mailto:gonca.danilo@gmal.com)

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
