### ISSUE TITLE
[Encurtador de URL] NestJS + Node.js + TypeScript

### ISSUE THREAD

**Issue by rof20004** [backend-br/desafios#6]
## Repositório do Desafio
[encurtador-url](https://github.com/rof20004/encurtador-url)

## Stack

* NestJS
* Node.js
* TypeScript
* SQLite3
* Swagger

## Comentários

Resolvi participar do desafio para testar meus conhecimentos

## Contato 

Linkedin: https://www.linkedin.com/in/rodolfo-azevedo-98485b52/
E-mail: rof20004@gmail.com

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
