### ISSUE TITLE
[Criptografia] Node + TypeScript

### ISSUE THREAD

**Issue by rof20004** [backend-br/desafios#7]
## Repositório do Desafio
[api-criptografia](https://github.com/rof20004/api-criptografia)

## Stack

* NestJS
* Node.js
* TypeScript
* SQLite3
* Swagger

## Comentários

Resolvi participar do desafio para testar meus conhecimentos

## Contato 

Linkedin: https://www.linkedin.com/in/rodolfo-azevedo-98485b52/
E-mail: rof20004@gmail.com

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/cryptography/SOLUTIONS.md). Obrigado por contribuir :)
