### ISSUE TITLE
[encurtador-url] Java-SpringBoot-Hibernate

### ISSUE THREAD

**Issue by Raeski** [backend-br/desafios#9]
## Repositório do desafio 

https://github.com/Raeski/url-encurtator

## Stack 

- Java
- SpringBoot
- Hibernate
- JPA

## Comentários 

 

Projeto foi fácil de ser feito, criei os endpoints em que o usuário manda a url e é retornado um código em que ele pode usar para ser redirecionado para o link, mais informações sobre os endpoints estão no README.MD do projeto. :D

## Contato 

Meu LinkedIn https://www.linkedin.com/in/gustavo-raeski/

**Comment by gustavofreze** [comment]
O link para sua solução foi adicionado no [repositório](https://github.com/backend-br/desafios/blob/master/url-shortener/SOLUTIONS.md). Obrigado por contribuir :)
